GET http://localhost:3000


###
POST http://localhost:3000
Content-Type: application/json


{
    "name":"iq" ,
    "email":"iqbalexample.com" ,
    "addresses": [{
        "city": "Dhakar"  }],
        "skills":"Javascript, React, Node"
    
}
